### ISSUE TITLE
The following signatures were invalid: KEYEXPIRED 1495751596

### ISSUE THREAD

**Issue by osmanovv** [mutability/mutability-repo#1]
While updating my Raspberry Pi with `sudo apt-get update` I get

> W: GPG error: http://repo.mutability.co.uk wheezy InRelease: The following signatures were invalid: KEYEXPIRED 1495751596 KEYEXPIRED 1495751596 KEYEXPIRED 1495751596 KEYEXPIRED 1495751596 KEYEXPIRED 1495751596

message.

I have set up the repository previously as:

> $ wget https://github.com/mutability/mutability-repo/releases/download/v0.1.1/mutability-repo_0.1.1_armhf.deb
> $ sudo dpkg -i mutability-repo_0.1.1_armhf.deb

**Comment by mutability** [comment]
I need to retire this; it's not maintained.

**Comment by osmanovv** [comment]
Is there any alternative to this repo?

**Comment by mutability** [comment]
What software from it are you using? It'll all buildable from source.

**Comment by osmanovv** [comment]
I am using your version of dump1090, and like to update it with `apt-get`.

**Comment by mutability** [comment]
You'll need to build from source; the repository version was way out of date anyway..
